base:
  build: .
  ports:
    - "3035:3035"
  container_name: fw-teams
  environment:
    PORT: 3035
    NODE_PATH: app/src

mongo:
  image: mongo
  container_name: fw-teams-mongo
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    - $HOME/docker/data/fw-teams-api:/data/db
  restart: always
