develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "3035"
  environment:
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:3035
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    API_VERSION: v1
  command: develop
  volumes:
    - ./app:/opt/fw-teams/app
  links: 
    - mongo
mongo:
  extends:
    file: base.yml
    service: mongo
