version: "3"
services:
  develop:
    build: .
    container_name: fw-teams-develop
    ports:
        - "3035:3035"
    environment:
      PORT: 3035
      NODE_PATH: app/src
      CT_REGISTER_MODE: auto
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3035
      MONGO_PORT_27017_TCP_ADDR: mongo
      REDIS_PORT_6379_TCP_ADDR: redis
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      JWT_SECRET: reallyunguessablesecretkey
      API_VERSION: v1
      API_GATEWAY_URL: http://mymachine:9000
      API_GATEWAY_EXTERNAL_URL: http://mymachine:9000
      API_GATEWAY_QUEUE_URL: redis://mymachine:6379
      API_GATEWAY_QUEUE_NAME: mail
      APP_URL: http://mymachine:3035
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/opt/fw-teams/app
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:3.4
    container_name: fw-teams-mongo-develop
    ports:
      - "27022:27017"
    volumes:
      - $HOME/docker/data/fw-teams/mongodb:/data/db
    restart: always

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

