apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fw
  labels:
    name: fw-teams
  name: fw-teams
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: fw-teams
    spec:
      containers:
      - name: fw-teams
        image: vizzuality/fw-teams
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: PORT
            value: "3035"
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://fw-teams.fw.svc.cluster.local:3035
          - name: MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: TEAMS_MONGO_URI
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: API_GATEWAY_URL
            value: https://staging-api.globalforestwatch.org
          - name: API_GATEWAY_EXTERNAL_URL
            value: https://staging-api.globalforestwatch.org
          - name: API_GATEWAY_QUEUE_PROVIDER
            value: redis
          - name: API_GATEWAY_QUEUE_NAME
            value: mail_staging
          - name: API_GATEWAY_QUEUE_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: FW_TEAMS_JWT_SECRET
          - name: APP_URL
            value: http://localhost:3000

        ports:
          - containerPort: 3035

      restartPolicy: Always
